# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ircd/anope/anope-2.0.6-source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ircd/anope/anope-2.0.6-source/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ircd/anope/anope-2.0.6-source/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ircd/anope/anope-2.0.6-source/build/CMakeFiles /home/ircd/anope/anope-2.0.6-source/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ircd/anope/anope-2.0.6-source/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named services

# Build rule for target.
services: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 services
.PHONY : services

# fast build rule for target.
services/fast:
	$(MAKE) -f src/CMakeFiles/services.dir/build.make src/CMakeFiles/services.dir/build
.PHONY : services/fast

#=============================================================================
# Target rules for targets named anopesmtp

# Build rule for target.
anopesmtp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 anopesmtp
.PHONY : anopesmtp

# fast build rule for target.
anopesmtp/fast:
	$(MAKE) -f src/tools/CMakeFiles/anopesmtp.dir/build.make src/tools/CMakeFiles/anopesmtp.dir/build
.PHONY : anopesmtp/fast

#=============================================================================
# Target rules for targets named memoserv.so

# Build rule for target.
memoserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memoserv.so
.PHONY : memoserv.so

# fast build rule for target.
memoserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/memoserv.so.dir/build.make modules/CMakeFiles/memoserv.so.dir/build
.PHONY : memoserv.so/fast

#=============================================================================
# Target rules for targets named global.so

# Build rule for target.
global.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 global.so
.PHONY : global.so

# fast build rule for target.
global.so/fast:
	$(MAKE) -f modules/CMakeFiles/global.so.dir/build.make modules/CMakeFiles/global.so.dir/build
.PHONY : global.so/fast

#=============================================================================
# Target rules for targets named botserv.so

# Build rule for target.
botserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 botserv.so
.PHONY : botserv.so

# fast build rule for target.
botserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/botserv.so.dir/build.make modules/CMakeFiles/botserv.so.dir/build
.PHONY : botserv.so/fast

#=============================================================================
# Target rules for targets named unreal4.so

# Build rule for target.
unreal4.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unreal4.so
.PHONY : unreal4.so

# fast build rule for target.
unreal4.so/fast:
	$(MAKE) -f modules/CMakeFiles/unreal4.so.dir/build.make modules/CMakeFiles/unreal4.so.dir/build
.PHONY : unreal4.so/fast

#=============================================================================
# Target rules for targets named unreal.so

# Build rule for target.
unreal.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unreal.so
.PHONY : unreal.so

# fast build rule for target.
unreal.so/fast:
	$(MAKE) -f modules/CMakeFiles/unreal.so.dir/build.make modules/CMakeFiles/unreal.so.dir/build
.PHONY : unreal.so/fast

#=============================================================================
# Target rules for targets named plexus.so

# Build rule for target.
plexus.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plexus.so
.PHONY : plexus.so

# fast build rule for target.
plexus.so/fast:
	$(MAKE) -f modules/CMakeFiles/plexus.so.dir/build.make modules/CMakeFiles/plexus.so.dir/build
.PHONY : plexus.so/fast

#=============================================================================
# Target rules for targets named inspircd20.so

# Build rule for target.
inspircd20.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inspircd20.so
.PHONY : inspircd20.so

# fast build rule for target.
inspircd20.so/fast:
	$(MAKE) -f modules/CMakeFiles/inspircd20.so.dir/build.make modules/CMakeFiles/inspircd20.so.dir/build
.PHONY : inspircd20.so/fast

#=============================================================================
# Target rules for targets named hybrid.so

# Build rule for target.
hybrid.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hybrid.so
.PHONY : hybrid.so

# fast build rule for target.
hybrid.so/fast:
	$(MAKE) -f modules/CMakeFiles/hybrid.so.dir/build.make modules/CMakeFiles/hybrid.so.dir/build
.PHONY : hybrid.so/fast

#=============================================================================
# Target rules for targets named charybdis.so

# Build rule for target.
charybdis.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 charybdis.so
.PHONY : charybdis.so

# fast build rule for target.
charybdis.so/fast:
	$(MAKE) -f modules/CMakeFiles/charybdis.so.dir/build.make modules/CMakeFiles/charybdis.so.dir/build
.PHONY : charybdis.so/fast

#=============================================================================
# Target rules for targets named bahamut.so

# Build rule for target.
bahamut.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bahamut.so
.PHONY : bahamut.so

# fast build rule for target.
bahamut.so/fast:
	$(MAKE) -f modules/CMakeFiles/bahamut.so.dir/build.make modules/CMakeFiles/bahamut.so.dir/build
.PHONY : bahamut.so/fast

#=============================================================================
# Target rules for targets named m_xmlrpc.so

# Build rule for target.
m_xmlrpc.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_xmlrpc.so
.PHONY : m_xmlrpc.so

# fast build rule for target.
m_xmlrpc.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_xmlrpc.so.dir/build.make modules/CMakeFiles/m_xmlrpc.so.dir/build
.PHONY : m_xmlrpc.so/fast

#=============================================================================
# Target rules for targets named m_sql_authentication.so

# Build rule for target.
m_sql_authentication.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_sql_authentication.so
.PHONY : m_sql_authentication.so

# fast build rule for target.
m_sql_authentication.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_sql_authentication.so.dir/build.make modules/CMakeFiles/m_sql_authentication.so.dir/build
.PHONY : m_sql_authentication.so/fast

#=============================================================================
# Target rules for targets named m_regex_posix.so

# Build rule for target.
m_regex_posix.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_regex_posix.so
.PHONY : m_regex_posix.so

# fast build rule for target.
m_regex_posix.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_regex_posix.so.dir/build.make modules/CMakeFiles/m_regex_posix.so.dir/build
.PHONY : m_regex_posix.so/fast

#=============================================================================
# Target rules for targets named m_redis.so

# Build rule for target.
m_redis.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_redis.so
.PHONY : m_redis.so

# fast build rule for target.
m_redis.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_redis.so.dir/build.make modules/CMakeFiles/m_redis.so.dir/build
.PHONY : m_redis.so/fast

#=============================================================================
# Target rules for targets named m_proxyscan.so

# Build rule for target.
m_proxyscan.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_proxyscan.so
.PHONY : m_proxyscan.so

# fast build rule for target.
m_proxyscan.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_proxyscan.so.dir/build.make modules/CMakeFiles/m_proxyscan.so.dir/build
.PHONY : m_proxyscan.so/fast

#=============================================================================
# Target rules for targets named m_helpchan.so

# Build rule for target.
m_helpchan.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_helpchan.so
.PHONY : m_helpchan.so

# fast build rule for target.
m_helpchan.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_helpchan.so.dir/build.make modules/CMakeFiles/m_helpchan.so.dir/build
.PHONY : m_helpchan.so/fast

#=============================================================================
# Target rules for targets named m_dnsbl.so

# Build rule for target.
m_dnsbl.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_dnsbl.so
.PHONY : m_dnsbl.so

# fast build rule for target.
m_dnsbl.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_dnsbl.so.dir/build.make modules/CMakeFiles/m_dnsbl.so.dir/build
.PHONY : m_dnsbl.so/fast

#=============================================================================
# Target rules for targets named fantasy.so

# Build rule for target.
fantasy.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fantasy.so
.PHONY : fantasy.so

# fast build rule for target.
fantasy.so/fast:
	$(MAKE) -f modules/CMakeFiles/fantasy.so.dir/build.make modules/CMakeFiles/fantasy.so.dir/build
.PHONY : fantasy.so/fast

#=============================================================================
# Target rules for targets named ns_maxemail.so

# Build rule for target.
ns_maxemail.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_maxemail.so
.PHONY : ns_maxemail.so

# fast build rule for target.
ns_maxemail.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_maxemail.so.dir/build.make modules/CMakeFiles/ns_maxemail.so.dir/build
.PHONY : ns_maxemail.so/fast

#=============================================================================
# Target rules for targets named enc_sha256.so

# Build rule for target.
enc_sha256.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_sha256.so
.PHONY : enc_sha256.so

# fast build rule for target.
enc_sha256.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_sha256.so.dir/build.make modules/CMakeFiles/enc_sha256.so.dir/build
.PHONY : enc_sha256.so/fast

#=============================================================================
# Target rules for targets named enc_sha1.so

# Build rule for target.
enc_sha1.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_sha1.so
.PHONY : enc_sha1.so

# fast build rule for target.
enc_sha1.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_sha1.so.dir/build.make modules/CMakeFiles/enc_sha1.so.dir/build
.PHONY : enc_sha1.so/fast

#=============================================================================
# Target rules for targets named enc_old.so

# Build rule for target.
enc_old.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_old.so
.PHONY : enc_old.so

# fast build rule for target.
enc_old.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_old.so.dir/build.make modules/CMakeFiles/enc_old.so.dir/build
.PHONY : enc_old.so/fast

#=============================================================================
# Target rules for targets named enc_md5.so

# Build rule for target.
enc_md5.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_md5.so
.PHONY : enc_md5.so

# fast build rule for target.
enc_md5.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_md5.so.dir/build.make modules/CMakeFiles/enc_md5.so.dir/build
.PHONY : enc_md5.so/fast

#=============================================================================
# Target rules for targets named db_sql_live.so

# Build rule for target.
db_sql_live.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_sql_live.so
.PHONY : db_sql_live.so

# fast build rule for target.
db_sql_live.so/fast:
	$(MAKE) -f modules/CMakeFiles/db_sql_live.so.dir/build.make modules/CMakeFiles/db_sql_live.so.dir/build
.PHONY : db_sql_live.so/fast

#=============================================================================
# Target rules for targets named db_sql.so

# Build rule for target.
db_sql.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_sql.so
.PHONY : db_sql.so

# fast build rule for target.
db_sql.so/fast:
	$(MAKE) -f modules/CMakeFiles/db_sql.so.dir/build.make modules/CMakeFiles/db_sql.so.dir/build
.PHONY : db_sql.so/fast

#=============================================================================
# Target rules for targets named db_old.so

# Build rule for target.
db_old.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_old.so
.PHONY : db_old.so

# fast build rule for target.
db_old.so/fast:
	$(MAKE) -f modules/CMakeFiles/db_old.so.dir/build.make modules/CMakeFiles/db_old.so.dir/build
.PHONY : db_old.so/fast

#=============================================================================
# Target rules for targets named db_flatfile.so

# Build rule for target.
db_flatfile.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_flatfile.so
.PHONY : db_flatfile.so

# fast build rule for target.
db_flatfile.so/fast:
	$(MAKE) -f modules/CMakeFiles/db_flatfile.so.dir/build.make modules/CMakeFiles/db_flatfile.so.dir/build
.PHONY : db_flatfile.so/fast

#=============================================================================
# Target rules for targets named os_update.so

# Build rule for target.
os_update.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_update.so
.PHONY : os_update.so

# fast build rule for target.
os_update.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_update.so.dir/build.make modules/CMakeFiles/os_update.so.dir/build
.PHONY : os_update.so/fast

#=============================================================================
# Target rules for targets named os_stats.so

# Build rule for target.
os_stats.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_stats.so
.PHONY : os_stats.so

# fast build rule for target.
os_stats.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_stats.so.dir/build.make modules/CMakeFiles/os_stats.so.dir/build
.PHONY : os_stats.so/fast

#=============================================================================
# Target rules for targets named os_reload.so

# Build rule for target.
os_reload.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_reload.so
.PHONY : os_reload.so

# fast build rule for target.
os_reload.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_reload.so.dir/build.make modules/CMakeFiles/os_reload.so.dir/build
.PHONY : os_reload.so/fast

#=============================================================================
# Target rules for targets named os_oper.so

# Build rule for target.
os_oper.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_oper.so
.PHONY : os_oper.so

# fast build rule for target.
os_oper.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_oper.so.dir/build.make modules/CMakeFiles/os_oper.so.dir/build
.PHONY : os_oper.so/fast

#=============================================================================
# Target rules for targets named hs_set.so

# Build rule for target.
hs_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_set.so
.PHONY : hs_set.so

# fast build rule for target.
hs_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_set.so.dir/build.make modules/CMakeFiles/hs_set.so.dir/build
.PHONY : hs_set.so/fast

#=============================================================================
# Target rules for targets named cs_mode.so

# Build rule for target.
cs_mode.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_mode.so
.PHONY : cs_mode.so

# fast build rule for target.
cs_mode.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_mode.so.dir/build.make modules/CMakeFiles/cs_mode.so.dir/build
.PHONY : cs_mode.so/fast

#=============================================================================
# Target rules for targets named ms_list.so

# Build rule for target.
ms_list.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_list.so
.PHONY : ms_list.so

# fast build rule for target.
ms_list.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_list.so.dir/build.make modules/CMakeFiles/ms_list.so.dir/build
.PHONY : ms_list.so/fast

#=============================================================================
# Target rules for targets named ns_getemail.so

# Build rule for target.
ns_getemail.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_getemail.so
.PHONY : ns_getemail.so

# fast build rule for target.
ns_getemail.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_getemail.so.dir/build.make modules/CMakeFiles/ns_getemail.so.dir/build
.PHONY : ns_getemail.so/fast

#=============================================================================
# Target rules for targets named cs_updown.so

# Build rule for target.
cs_updown.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_updown.so
.PHONY : cs_updown.so

# fast build rule for target.
cs_updown.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_updown.so.dir/build.make modules/CMakeFiles/cs_updown.so.dir/build
.PHONY : cs_updown.so/fast

#=============================================================================
# Target rules for targets named os_chankill.so

# Build rule for target.
os_chankill.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_chankill.so
.PHONY : os_chankill.so

# fast build rule for target.
os_chankill.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_chankill.so.dir/build.make modules/CMakeFiles/os_chankill.so.dir/build
.PHONY : os_chankill.so/fast

#=============================================================================
# Target rules for targets named os_shutdown.so

# Build rule for target.
os_shutdown.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_shutdown.so
.PHONY : os_shutdown.so

# fast build rule for target.
os_shutdown.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_shutdown.so.dir/build.make modules/CMakeFiles/os_shutdown.so.dir/build
.PHONY : os_shutdown.so/fast

#=============================================================================
# Target rules for targets named os_ignore.so

# Build rule for target.
os_ignore.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_ignore.so
.PHONY : os_ignore.so

# fast build rule for target.
os_ignore.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_ignore.so.dir/build.make modules/CMakeFiles/os_ignore.so.dir/build
.PHONY : os_ignore.so/fast

#=============================================================================
# Target rules for targets named ratbox.so

# Build rule for target.
ratbox.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ratbox.so
.PHONY : ratbox.so

# fast build rule for target.
ratbox.so/fast:
	$(MAKE) -f modules/CMakeFiles/ratbox.so.dir/build.make modules/CMakeFiles/ratbox.so.dir/build
.PHONY : ratbox.so/fast

#=============================================================================
# Target rules for targets named cs_suspend.so

# Build rule for target.
cs_suspend.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_suspend.so
.PHONY : cs_suspend.so

# fast build rule for target.
cs_suspend.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_suspend.so.dir/build.make modules/CMakeFiles/cs_suspend.so.dir/build
.PHONY : cs_suspend.so/fast

#=============================================================================
# Target rules for targets named cs_xop.so

# Build rule for target.
cs_xop.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_xop.so
.PHONY : cs_xop.so

# fast build rule for target.
cs_xop.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_xop.so.dir/build.make modules/CMakeFiles/cs_xop.so.dir/build
.PHONY : cs_xop.so/fast

#=============================================================================
# Target rules for targets named m_dns.so

# Build rule for target.
m_dns.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_dns.so
.PHONY : m_dns.so

# fast build rule for target.
m_dns.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_dns.so.dir/build.make modules/CMakeFiles/m_dns.so.dir/build
.PHONY : m_dns.so/fast

#=============================================================================
# Target rules for targets named cs_sync.so

# Build rule for target.
cs_sync.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_sync.so
.PHONY : cs_sync.so

# fast build rule for target.
cs_sync.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_sync.so.dir/build.make modules/CMakeFiles/cs_sync.so.dir/build
.PHONY : cs_sync.so/fast

#=============================================================================
# Target rules for targets named os_noop.so

# Build rule for target.
os_noop.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_noop.so
.PHONY : os_noop.so

# fast build rule for target.
os_noop.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_noop.so.dir/build.make modules/CMakeFiles/os_noop.so.dir/build
.PHONY : os_noop.so/fast

#=============================================================================
# Target rules for targets named ns_access.so

# Build rule for target.
ns_access.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_access.so
.PHONY : ns_access.so

# fast build rule for target.
ns_access.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_access.so.dir/build.make modules/CMakeFiles/ns_access.so.dir/build
.PHONY : ns_access.so/fast

#=============================================================================
# Target rules for targets named cs_unban.so

# Build rule for target.
cs_unban.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_unban.so
.PHONY : cs_unban.so

# fast build rule for target.
cs_unban.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_unban.so.dir/build.make modules/CMakeFiles/cs_unban.so.dir/build
.PHONY : cs_unban.so/fast

#=============================================================================
# Target rules for targets named cs_access.so

# Build rule for target.
cs_access.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_access.so
.PHONY : cs_access.so

# fast build rule for target.
cs_access.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_access.so.dir/build.make modules/CMakeFiles/cs_access.so.dir/build
.PHONY : cs_access.so/fast

#=============================================================================
# Target rules for targets named bs_control.so

# Build rule for target.
bs_control.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_control.so
.PHONY : bs_control.so

# fast build rule for target.
bs_control.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_control.so.dir/build.make modules/CMakeFiles/bs_control.so.dir/build
.PHONY : bs_control.so/fast

#=============================================================================
# Target rules for targets named ns_getpass.so

# Build rule for target.
ns_getpass.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_getpass.so
.PHONY : ns_getpass.so

# fast build rule for target.
ns_getpass.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_getpass.so.dir/build.make modules/CMakeFiles/ns_getpass.so.dir/build
.PHONY : ns_getpass.so/fast

#=============================================================================
# Target rules for targets named bs_botlist.so

# Build rule for target.
bs_botlist.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_botlist.so
.PHONY : bs_botlist.so

# fast build rule for target.
bs_botlist.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_botlist.so.dir/build.make modules/CMakeFiles/bs_botlist.so.dir/build
.PHONY : bs_botlist.so/fast

#=============================================================================
# Target rules for targets named hs_del.so

# Build rule for target.
hs_del.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_del.so
.PHONY : hs_del.so

# fast build rule for target.
hs_del.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_del.so.dir/build.make modules/CMakeFiles/hs_del.so.dir/build
.PHONY : hs_del.so/fast

#=============================================================================
# Target rules for targets named cs_status.so

# Build rule for target.
cs_status.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_status.so
.PHONY : cs_status.so

# fast build rule for target.
cs_status.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_status.so.dir/build.make modules/CMakeFiles/cs_status.so.dir/build
.PHONY : cs_status.so/fast

#=============================================================================
# Target rules for targets named m_xmlrpc_main.so

# Build rule for target.
m_xmlrpc_main.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_xmlrpc_main.so
.PHONY : m_xmlrpc_main.so

# fast build rule for target.
m_xmlrpc_main.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_xmlrpc_main.so.dir/build.make modules/CMakeFiles/m_xmlrpc_main.so.dir/build
.PHONY : m_xmlrpc_main.so/fast

#=============================================================================
# Target rules for targets named bs_bot.so

# Build rule for target.
bs_bot.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_bot.so
.PHONY : bs_bot.so

# fast build rule for target.
bs_bot.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_bot.so.dir/build.make modules/CMakeFiles/bs_bot.so.dir/build
.PHONY : bs_bot.so/fast

#=============================================================================
# Target rules for targets named cs_akick.so

# Build rule for target.
cs_akick.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_akick.so
.PHONY : cs_akick.so

# fast build rule for target.
cs_akick.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_akick.so.dir/build.make modules/CMakeFiles/cs_akick.so.dir/build
.PHONY : cs_akick.so/fast

#=============================================================================
# Target rules for targets named os_svs.so

# Build rule for target.
os_svs.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_svs.so
.PHONY : os_svs.so

# fast build rule for target.
os_svs.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_svs.so.dir/build.make modules/CMakeFiles/os_svs.so.dir/build
.PHONY : os_svs.so/fast

#=============================================================================
# Target rules for targets named cs_getkey.so

# Build rule for target.
cs_getkey.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_getkey.so
.PHONY : cs_getkey.so

# fast build rule for target.
cs_getkey.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_getkey.so.dir/build.make modules/CMakeFiles/cs_getkey.so.dir/build
.PHONY : cs_getkey.so/fast

#=============================================================================
# Target rules for targets named hs_on.so

# Build rule for target.
hs_on.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_on.so
.PHONY : hs_on.so

# fast build rule for target.
hs_on.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_on.so.dir/build.make modules/CMakeFiles/hs_on.so.dir/build
.PHONY : hs_on.so/fast

#=============================================================================
# Target rules for targets named operserv.so

# Build rule for target.
operserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 operserv.so
.PHONY : operserv.so

# fast build rule for target.
operserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/operserv.so.dir/build.make modules/CMakeFiles/operserv.so.dir/build
.PHONY : operserv.so/fast

#=============================================================================
# Target rules for targets named os_config.so

# Build rule for target.
os_config.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_config.so
.PHONY : os_config.so

# fast build rule for target.
os_config.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_config.so.dir/build.make modules/CMakeFiles/os_config.so.dir/build
.PHONY : os_config.so/fast

#=============================================================================
# Target rules for targets named hs_off.so

# Build rule for target.
hs_off.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_off.so
.PHONY : hs_off.so

# fast build rule for target.
hs_off.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_off.so.dir/build.make modules/CMakeFiles/hs_off.so.dir/build
.PHONY : hs_off.so/fast

#=============================================================================
# Target rules for targets named cs_clone.so

# Build rule for target.
cs_clone.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_clone.so
.PHONY : cs_clone.so

# fast build rule for target.
cs_clone.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_clone.so.dir/build.make modules/CMakeFiles/cs_clone.so.dir/build
.PHONY : cs_clone.so/fast

#=============================================================================
# Target rules for targets named cs_set_misc.so

# Build rule for target.
cs_set_misc.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_set_misc.so
.PHONY : cs_set_misc.so

# fast build rule for target.
cs_set_misc.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_set_misc.so.dir/build.make modules/CMakeFiles/cs_set_misc.so.dir/build
.PHONY : cs_set_misc.so/fast

#=============================================================================
# Target rules for targets named ms_del.so

# Build rule for target.
ms_del.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_del.so
.PHONY : ms_del.so

# fast build rule for target.
ms_del.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_del.so.dir/build.make modules/CMakeFiles/ms_del.so.dir/build
.PHONY : ms_del.so/fast

#=============================================================================
# Target rules for targets named ns_recover.so

# Build rule for target.
ns_recover.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_recover.so
.PHONY : ns_recover.so

# fast build rule for target.
ns_recover.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_recover.so.dir/build.make modules/CMakeFiles/ns_recover.so.dir/build
.PHONY : ns_recover.so/fast

#=============================================================================
# Target rules for targets named bs_assign.so

# Build rule for target.
bs_assign.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_assign.so
.PHONY : bs_assign.so

# fast build rule for target.
bs_assign.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_assign.so.dir/build.make modules/CMakeFiles/bs_assign.so.dir/build
.PHONY : bs_assign.so/fast

#=============================================================================
# Target rules for targets named bs_badwords.so

# Build rule for target.
bs_badwords.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_badwords.so
.PHONY : bs_badwords.so

# fast build rule for target.
bs_badwords.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_badwords.so.dir/build.make modules/CMakeFiles/bs_badwords.so.dir/build
.PHONY : bs_badwords.so/fast

#=============================================================================
# Target rules for targets named bs_autoassign.so

# Build rule for target.
bs_autoassign.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_autoassign.so
.PHONY : bs_autoassign.so

# fast build rule for target.
bs_autoassign.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_autoassign.so.dir/build.make modules/CMakeFiles/bs_autoassign.so.dir/build
.PHONY : bs_autoassign.so/fast

#=============================================================================
# Target rules for targets named ms_rsend.so

# Build rule for target.
ms_rsend.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_rsend.so
.PHONY : ms_rsend.so

# fast build rule for target.
ms_rsend.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_rsend.so.dir/build.make modules/CMakeFiles/ms_rsend.so.dir/build
.PHONY : ms_rsend.so/fast

#=============================================================================
# Target rules for targets named cs_info.so

# Build rule for target.
cs_info.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_info.so
.PHONY : cs_info.so

# fast build rule for target.
cs_info.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_info.so.dir/build.make modules/CMakeFiles/cs_info.so.dir/build
.PHONY : cs_info.so/fast

#=============================================================================
# Target rules for targets named cs_invite.so

# Build rule for target.
cs_invite.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_invite.so
.PHONY : cs_invite.so

# fast build rule for target.
cs_invite.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_invite.so.dir/build.make modules/CMakeFiles/cs_invite.so.dir/build
.PHONY : cs_invite.so/fast

#=============================================================================
# Target rules for targets named os_akill.so

# Build rule for target.
os_akill.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_akill.so
.PHONY : os_akill.so

# fast build rule for target.
os_akill.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_akill.so.dir/build.make modules/CMakeFiles/os_akill.so.dir/build
.PHONY : os_akill.so/fast

#=============================================================================
# Target rules for targets named gl_global.so

# Build rule for target.
gl_global.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gl_global.so
.PHONY : gl_global.so

# fast build rule for target.
gl_global.so/fast:
	$(MAKE) -f modules/CMakeFiles/gl_global.so.dir/build.make modules/CMakeFiles/gl_global.so.dir/build
.PHONY : gl_global.so/fast

#=============================================================================
# Target rules for targets named os_set.so

# Build rule for target.
os_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_set.so
.PHONY : os_set.so

# fast build rule for target.
os_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_set.so.dir/build.make modules/CMakeFiles/os_set.so.dir/build
.PHONY : os_set.so/fast

#=============================================================================
# Target rules for targets named bs_kick.so

# Build rule for target.
bs_kick.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_kick.so
.PHONY : bs_kick.so

# fast build rule for target.
bs_kick.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_kick.so.dir/build.make modules/CMakeFiles/bs_kick.so.dir/build
.PHONY : bs_kick.so/fast

#=============================================================================
# Target rules for targets named hs_list.so

# Build rule for target.
hs_list.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_list.so
.PHONY : hs_list.so

# fast build rule for target.
hs_list.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_list.so.dir/build.make modules/CMakeFiles/hs_list.so.dir/build
.PHONY : hs_list.so/fast

#=============================================================================
# Target rules for targets named bs_set.so

# Build rule for target.
bs_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_set.so
.PHONY : bs_set.so

# fast build rule for target.
bs_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_set.so.dir/build.make modules/CMakeFiles/bs_set.so.dir/build
.PHONY : bs_set.so/fast

#=============================================================================
# Target rules for targets named os_oline.so

# Build rule for target.
os_oline.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_oline.so
.PHONY : os_oline.so

# fast build rule for target.
os_oline.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_oline.so.dir/build.make modules/CMakeFiles/os_oline.so.dir/build
.PHONY : os_oline.so/fast

#=============================================================================
# Target rules for targets named cs_ban.so

# Build rule for target.
cs_ban.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_ban.so
.PHONY : cs_ban.so

# fast build rule for target.
cs_ban.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_ban.so.dir/build.make modules/CMakeFiles/cs_ban.so.dir/build
.PHONY : cs_ban.so/fast

#=============================================================================
# Target rules for targets named cs_statusupdate.so

# Build rule for target.
cs_statusupdate.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_statusupdate.so
.PHONY : cs_statusupdate.so

# fast build rule for target.
cs_statusupdate.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_statusupdate.so.dir/build.make modules/CMakeFiles/cs_statusupdate.so.dir/build
.PHONY : cs_statusupdate.so/fast

#=============================================================================
# Target rules for targets named os_info.so

# Build rule for target.
os_info.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_info.so
.PHONY : os_info.so

# fast build rule for target.
os_info.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_info.so.dir/build.make modules/CMakeFiles/os_info.so.dir/build
.PHONY : os_info.so/fast

#=============================================================================
# Target rules for targets named nickserv.so

# Build rule for target.
nickserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nickserv.so
.PHONY : nickserv.so

# fast build rule for target.
nickserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/nickserv.so.dir/build.make modules/CMakeFiles/nickserv.so.dir/build
.PHONY : nickserv.so/fast

#=============================================================================
# Target rules for targets named cs_enforce.so

# Build rule for target.
cs_enforce.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_enforce.so
.PHONY : cs_enforce.so

# fast build rule for target.
cs_enforce.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_enforce.so.dir/build.make modules/CMakeFiles/cs_enforce.so.dir/build
.PHONY : cs_enforce.so/fast

#=============================================================================
# Target rules for targets named os_logsearch.so

# Build rule for target.
os_logsearch.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_logsearch.so
.PHONY : os_logsearch.so

# fast build rule for target.
os_logsearch.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_logsearch.so.dir/build.make modules/CMakeFiles/os_logsearch.so.dir/build
.PHONY : os_logsearch.so/fast

#=============================================================================
# Target rules for targets named os_sxline.so

# Build rule for target.
os_sxline.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_sxline.so
.PHONY : os_sxline.so

# fast build rule for target.
os_sxline.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_sxline.so.dir/build.make modules/CMakeFiles/os_sxline.so.dir/build
.PHONY : os_sxline.so/fast

#=============================================================================
# Target rules for targets named os_dns.so

# Build rule for target.
os_dns.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_dns.so
.PHONY : os_dns.so

# fast build rule for target.
os_dns.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_dns.so.dir/build.make modules/CMakeFiles/os_dns.so.dir/build
.PHONY : os_dns.so/fast

#=============================================================================
# Target rules for targets named cs_list.so

# Build rule for target.
cs_list.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_list.so
.PHONY : cs_list.so

# fast build rule for target.
cs_list.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_list.so.dir/build.make modules/CMakeFiles/cs_list.so.dir/build
.PHONY : cs_list.so/fast

#=============================================================================
# Target rules for targets named cs_topic.so

# Build rule for target.
cs_topic.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_topic.so
.PHONY : cs_topic.so

# fast build rule for target.
cs_topic.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_topic.so.dir/build.make modules/CMakeFiles/cs_topic.so.dir/build
.PHONY : cs_topic.so/fast

#=============================================================================
# Target rules for targets named greet.so

# Build rule for target.
greet.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greet.so
.PHONY : greet.so

# fast build rule for target.
greet.so/fast:
	$(MAKE) -f modules/CMakeFiles/greet.so.dir/build.make modules/CMakeFiles/greet.so.dir/build
.PHONY : greet.so/fast

#=============================================================================
# Target rules for targets named hostserv.so

# Build rule for target.
hostserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hostserv.so
.PHONY : hostserv.so

# fast build rule for target.
hostserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/hostserv.so.dir/build.make modules/CMakeFiles/hostserv.so.dir/build
.PHONY : hostserv.so/fast

#=============================================================================
# Target rules for targets named cs_log.so

# Build rule for target.
cs_log.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_log.so
.PHONY : cs_log.so

# fast build rule for target.
cs_log.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_log.so.dir/build.make modules/CMakeFiles/cs_log.so.dir/build
.PHONY : cs_log.so/fast

#=============================================================================
# Target rules for targets named cs_drop.so

# Build rule for target.
cs_drop.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_drop.so
.PHONY : cs_drop.so

# fast build rule for target.
cs_drop.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_drop.so.dir/build.make modules/CMakeFiles/cs_drop.so.dir/build
.PHONY : cs_drop.so/fast

#=============================================================================
# Target rules for targets named cs_entrymsg.so

# Build rule for target.
cs_entrymsg.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_entrymsg.so
.PHONY : cs_entrymsg.so

# fast build rule for target.
cs_entrymsg.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_entrymsg.so.dir/build.make modules/CMakeFiles/cs_entrymsg.so.dir/build
.PHONY : cs_entrymsg.so/fast

#=============================================================================
# Target rules for targets named bs_info.so

# Build rule for target.
bs_info.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bs_info.so
.PHONY : bs_info.so

# fast build rule for target.
bs_info.so/fast:
	$(MAKE) -f modules/CMakeFiles/bs_info.so.dir/build.make modules/CMakeFiles/bs_info.so.dir/build
.PHONY : bs_info.so/fast

#=============================================================================
# Target rules for targets named ms_send.so

# Build rule for target.
ms_send.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_send.so
.PHONY : ms_send.so

# fast build rule for target.
ms_send.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_send.so.dir/build.make modules/CMakeFiles/ms_send.so.dir/build
.PHONY : ms_send.so/fast

#=============================================================================
# Target rules for targets named hs_group.so

# Build rule for target.
hs_group.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_group.so
.PHONY : hs_group.so

# fast build rule for target.
hs_group.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_group.so.dir/build.make modules/CMakeFiles/hs_group.so.dir/build
.PHONY : hs_group.so/fast

#=============================================================================
# Target rules for targets named m_ssl_openssl.so

# Build rule for target.
m_ssl_openssl.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_ssl_openssl.so
.PHONY : m_ssl_openssl.so

# fast build rule for target.
m_ssl_openssl.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_ssl_openssl.so.dir/build.make modules/CMakeFiles/m_ssl_openssl.so.dir/build
.PHONY : m_ssl_openssl.so/fast

#=============================================================================
# Target rules for targets named cs_set.so

# Build rule for target.
cs_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_set.so
.PHONY : cs_set.so

# fast build rule for target.
cs_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_set.so.dir/build.make modules/CMakeFiles/cs_set.so.dir/build
.PHONY : cs_set.so/fast

#=============================================================================
# Target rules for targets named os_module.so

# Build rule for target.
os_module.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_module.so
.PHONY : os_module.so

# fast build rule for target.
os_module.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_module.so.dir/build.make modules/CMakeFiles/os_module.so.dir/build
.PHONY : os_module.so/fast

#=============================================================================
# Target rules for targets named cs_flags.so

# Build rule for target.
cs_flags.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_flags.so
.PHONY : cs_flags.so

# fast build rule for target.
cs_flags.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_flags.so.dir/build.make modules/CMakeFiles/cs_flags.so.dir/build
.PHONY : cs_flags.so/fast

#=============================================================================
# Target rules for targets named ns_alist.so

# Build rule for target.
ns_alist.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_alist.so
.PHONY : ns_alist.so

# fast build rule for target.
ns_alist.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_alist.so.dir/build.make modules/CMakeFiles/ns_alist.so.dir/build
.PHONY : ns_alist.so/fast

#=============================================================================
# Target rules for targets named help.so

# Build rule for target.
help.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 help.so
.PHONY : help.so

# fast build rule for target.
help.so/fast:
	$(MAKE) -f modules/CMakeFiles/help.so.dir/build.make modules/CMakeFiles/help.so.dir/build
.PHONY : help.so/fast

#=============================================================================
# Target rules for targets named ms_check.so

# Build rule for target.
ms_check.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_check.so
.PHONY : ms_check.so

# fast build rule for target.
ms_check.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_check.so.dir/build.make modules/CMakeFiles/ms_check.so.dir/build
.PHONY : ms_check.so/fast

#=============================================================================
# Target rules for targets named inspircd12.so

# Build rule for target.
inspircd12.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inspircd12.so
.PHONY : inspircd12.so

# fast build rule for target.
inspircd12.so/fast:
	$(MAKE) -f modules/CMakeFiles/inspircd12.so.dir/build.make modules/CMakeFiles/inspircd12.so.dir/build
.PHONY : inspircd12.so/fast

#=============================================================================
# Target rules for targets named ms_ignore.so

# Build rule for target.
ms_ignore.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_ignore.so
.PHONY : ms_ignore.so

# fast build rule for target.
ms_ignore.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_ignore.so.dir/build.make modules/CMakeFiles/ms_ignore.so.dir/build
.PHONY : ms_ignore.so/fast

#=============================================================================
# Target rules for targets named cs_kick.so

# Build rule for target.
cs_kick.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_kick.so
.PHONY : cs_kick.so

# fast build rule for target.
cs_kick.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_kick.so.dir/build.make modules/CMakeFiles/cs_kick.so.dir/build
.PHONY : cs_kick.so/fast

#=============================================================================
# Target rules for targets named ms_read.so

# Build rule for target.
ms_read.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_read.so
.PHONY : ms_read.so

# fast build rule for target.
ms_read.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_read.so.dir/build.make modules/CMakeFiles/ms_read.so.dir/build
.PHONY : ms_read.so/fast

#=============================================================================
# Target rules for targets named ms_sendall.so

# Build rule for target.
ms_sendall.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_sendall.so
.PHONY : ms_sendall.so

# fast build rule for target.
ms_sendall.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_sendall.so.dir/build.make modules/CMakeFiles/ms_sendall.so.dir/build
.PHONY : ms_sendall.so/fast

#=============================================================================
# Target rules for targets named ms_set.so

# Build rule for target.
ms_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_set.so
.PHONY : ms_set.so

# fast build rule for target.
ms_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_set.so.dir/build.make modules/CMakeFiles/ms_set.so.dir/build
.PHONY : ms_set.so/fast

#=============================================================================
# Target rules for targets named enc_bcrypt.so

# Build rule for target.
enc_bcrypt.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_bcrypt.so
.PHONY : enc_bcrypt.so

# fast build rule for target.
enc_bcrypt.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_bcrypt.so.dir/build.make modules/CMakeFiles/enc_bcrypt.so.dir/build
.PHONY : enc_bcrypt.so/fast

#=============================================================================
# Target rules for targets named ns_update.so

# Build rule for target.
ns_update.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_update.so
.PHONY : ns_update.so

# fast build rule for target.
ns_update.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_update.so.dir/build.make modules/CMakeFiles/ns_update.so.dir/build
.PHONY : ns_update.so/fast

#=============================================================================
# Target rules for targets named ms_cancel.so

# Build rule for target.
ms_cancel.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_cancel.so
.PHONY : ms_cancel.so

# fast build rule for target.
ms_cancel.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_cancel.so.dir/build.make modules/CMakeFiles/ms_cancel.so.dir/build
.PHONY : ms_cancel.so/fast

#=============================================================================
# Target rules for targets named os_kick.so

# Build rule for target.
os_kick.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_kick.so
.PHONY : os_kick.so

# fast build rule for target.
os_kick.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_kick.so.dir/build.make modules/CMakeFiles/os_kick.so.dir/build
.PHONY : os_kick.so/fast

#=============================================================================
# Target rules for targets named ms_staff.so

# Build rule for target.
ms_staff.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_staff.so
.PHONY : ms_staff.so

# fast build rule for target.
ms_staff.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_staff.so.dir/build.make modules/CMakeFiles/ms_staff.so.dir/build
.PHONY : ms_staff.so/fast

#=============================================================================
# Target rules for targets named ngircd.so

# Build rule for target.
ngircd.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngircd.so
.PHONY : ngircd.so

# fast build rule for target.
ngircd.so/fast:
	$(MAKE) -f modules/CMakeFiles/ngircd.so.dir/build.make modules/CMakeFiles/ngircd.so.dir/build
.PHONY : ngircd.so/fast

#=============================================================================
# Target rules for targets named m_sql_log.so

# Build rule for target.
m_sql_log.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_sql_log.so
.PHONY : m_sql_log.so

# fast build rule for target.
m_sql_log.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_sql_log.so.dir/build.make modules/CMakeFiles/m_sql_log.so.dir/build
.PHONY : m_sql_log.so/fast

#=============================================================================
# Target rules for targets named m_sasl.so

# Build rule for target.
m_sasl.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_sasl.so
.PHONY : m_sasl.so

# fast build rule for target.
m_sasl.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_sasl.so.dir/build.make modules/CMakeFiles/m_sasl.so.dir/build
.PHONY : m_sasl.so/fast

#=============================================================================
# Target rules for targets named os_session.so

# Build rule for target.
os_session.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_session.so
.PHONY : os_session.so

# fast build rule for target.
os_session.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_session.so.dir/build.make modules/CMakeFiles/os_session.so.dir/build
.PHONY : os_session.so/fast

#=============================================================================
# Target rules for targets named ns_ajoin.so

# Build rule for target.
ns_ajoin.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_ajoin.so
.PHONY : ns_ajoin.so

# fast build rule for target.
ns_ajoin.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_ajoin.so.dir/build.make modules/CMakeFiles/ns_ajoin.so.dir/build
.PHONY : ns_ajoin.so/fast

#=============================================================================
# Target rules for targets named ns_cert.so

# Build rule for target.
ns_cert.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_cert.so
.PHONY : ns_cert.so

# fast build rule for target.
ns_cert.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_cert.so.dir/build.make modules/CMakeFiles/ns_cert.so.dir/build
.PHONY : ns_cert.so/fast

#=============================================================================
# Target rules for targets named os_mode.so

# Build rule for target.
os_mode.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_mode.so
.PHONY : os_mode.so

# fast build rule for target.
os_mode.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_mode.so.dir/build.make modules/CMakeFiles/os_mode.so.dir/build
.PHONY : os_mode.so/fast

#=============================================================================
# Target rules for targets named m_mysql.so

# Build rule for target.
m_mysql.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_mysql.so
.PHONY : m_mysql.so

# fast build rule for target.
m_mysql.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_mysql.so.dir/build.make modules/CMakeFiles/m_mysql.so.dir/build
.PHONY : m_mysql.so/fast

#=============================================================================
# Target rules for targets named ns_drop.so

# Build rule for target.
ns_drop.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_drop.so
.PHONY : ns_drop.so

# fast build rule for target.
ns_drop.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_drop.so.dir/build.make modules/CMakeFiles/ns_drop.so.dir/build
.PHONY : ns_drop.so/fast

#=============================================================================
# Target rules for targets named ns_group.so

# Build rule for target.
ns_group.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_group.so
.PHONY : ns_group.so

# fast build rule for target.
ns_group.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_group.so.dir/build.make modules/CMakeFiles/ns_group.so.dir/build
.PHONY : ns_group.so/fast

#=============================================================================
# Target rules for targets named ns_resetpass.so

# Build rule for target.
ns_resetpass.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_resetpass.so
.PHONY : ns_resetpass.so

# fast build rule for target.
ns_resetpass.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_resetpass.so.dir/build.make modules/CMakeFiles/ns_resetpass.so.dir/build
.PHONY : ns_resetpass.so/fast

#=============================================================================
# Target rules for targets named os_list.so

# Build rule for target.
os_list.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_list.so
.PHONY : os_list.so

# fast build rule for target.
os_list.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_list.so.dir/build.make modules/CMakeFiles/os_list.so.dir/build
.PHONY : os_list.so/fast

#=============================================================================
# Target rules for targets named ns_identify.so

# Build rule for target.
ns_identify.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_identify.so
.PHONY : ns_identify.so

# fast build rule for target.
ns_identify.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_identify.so.dir/build.make modules/CMakeFiles/ns_identify.so.dir/build
.PHONY : ns_identify.so/fast

#=============================================================================
# Target rules for targets named os_login.so

# Build rule for target.
os_login.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_login.so
.PHONY : os_login.so

# fast build rule for target.
os_login.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_login.so.dir/build.make modules/CMakeFiles/os_login.so.dir/build
.PHONY : os_login.so/fast

#=============================================================================
# Target rules for targets named ns_info.so

# Build rule for target.
ns_info.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_info.so
.PHONY : ns_info.so

# fast build rule for target.
ns_info.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_info.so.dir/build.make modules/CMakeFiles/ns_info.so.dir/build
.PHONY : ns_info.so/fast

#=============================================================================
# Target rules for targets named ns_list.so

# Build rule for target.
ns_list.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_list.so
.PHONY : ns_list.so

# fast build rule for target.
ns_list.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_list.so.dir/build.make modules/CMakeFiles/ns_list.so.dir/build
.PHONY : ns_list.so/fast

#=============================================================================
# Target rules for targets named os_defcon.so

# Build rule for target.
os_defcon.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_defcon.so
.PHONY : os_defcon.so

# fast build rule for target.
os_defcon.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_defcon.so.dir/build.make modules/CMakeFiles/os_defcon.so.dir/build
.PHONY : os_defcon.so/fast

#=============================================================================
# Target rules for targets named ns_logout.so

# Build rule for target.
ns_logout.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_logout.so
.PHONY : ns_logout.so

# fast build rule for target.
ns_logout.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_logout.so.dir/build.make modules/CMakeFiles/ns_logout.so.dir/build
.PHONY : ns_logout.so/fast

#=============================================================================
# Target rules for targets named ns_register.so

# Build rule for target.
ns_register.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_register.so
.PHONY : ns_register.so

# fast build rule for target.
ns_register.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_register.so.dir/build.make modules/CMakeFiles/ns_register.so.dir/build
.PHONY : ns_register.so/fast

#=============================================================================
# Target rules for targets named cs_seen.so

# Build rule for target.
cs_seen.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_seen.so
.PHONY : cs_seen.so

# fast build rule for target.
cs_seen.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_seen.so.dir/build.make modules/CMakeFiles/cs_seen.so.dir/build
.PHONY : cs_seen.so/fast

#=============================================================================
# Target rules for targets named ns_set.so

# Build rule for target.
ns_set.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_set.so
.PHONY : ns_set.so

# fast build rule for target.
ns_set.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_set.so.dir/build.make modules/CMakeFiles/ns_set.so.dir/build
.PHONY : ns_set.so/fast

#=============================================================================
# Target rules for targets named ns_set_misc.so

# Build rule for target.
ns_set_misc.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_set_misc.so
.PHONY : ns_set_misc.so

# fast build rule for target.
ns_set_misc.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_set_misc.so.dir/build.make modules/CMakeFiles/ns_set_misc.so.dir/build
.PHONY : ns_set_misc.so/fast

#=============================================================================
# Target rules for targets named chanserv.so

# Build rule for target.
chanserv.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chanserv.so
.PHONY : chanserv.so

# fast build rule for target.
chanserv.so/fast:
	$(MAKE) -f modules/CMakeFiles/chanserv.so.dir/build.make modules/CMakeFiles/chanserv.so.dir/build
.PHONY : chanserv.so/fast

#=============================================================================
# Target rules for targets named db_redis.so

# Build rule for target.
db_redis.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_redis.so
.PHONY : db_redis.so

# fast build rule for target.
db_redis.so/fast:
	$(MAKE) -f modules/CMakeFiles/db_redis.so.dir/build.make modules/CMakeFiles/db_redis.so.dir/build
.PHONY : db_redis.so/fast

#=============================================================================
# Target rules for targets named os_kill.so

# Build rule for target.
os_kill.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_kill.so
.PHONY : os_kill.so

# fast build rule for target.
os_kill.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_kill.so.dir/build.make modules/CMakeFiles/os_kill.so.dir/build
.PHONY : os_kill.so/fast

#=============================================================================
# Target rules for targets named enc_none.so

# Build rule for target.
enc_none.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enc_none.so
.PHONY : enc_none.so

# fast build rule for target.
enc_none.so/fast:
	$(MAKE) -f modules/CMakeFiles/enc_none.so.dir/build.make modules/CMakeFiles/enc_none.so.dir/build
.PHONY : enc_none.so/fast

#=============================================================================
# Target rules for targets named cs_register.so

# Build rule for target.
cs_register.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs_register.so
.PHONY : cs_register.so

# fast build rule for target.
cs_register.so/fast:
	$(MAKE) -f modules/CMakeFiles/cs_register.so.dir/build.make modules/CMakeFiles/cs_register.so.dir/build
.PHONY : cs_register.so/fast

#=============================================================================
# Target rules for targets named ns_status.so

# Build rule for target.
ns_status.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_status.so
.PHONY : ns_status.so

# fast build rule for target.
ns_status.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_status.so.dir/build.make modules/CMakeFiles/ns_status.so.dir/build
.PHONY : ns_status.so/fast

#=============================================================================
# Target rules for targets named ns_suspend.so

# Build rule for target.
ns_suspend.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ns_suspend.so
.PHONY : ns_suspend.so

# fast build rule for target.
ns_suspend.so/fast:
	$(MAKE) -f modules/CMakeFiles/ns_suspend.so.dir/build.make modules/CMakeFiles/ns_suspend.so.dir/build
.PHONY : ns_suspend.so/fast

#=============================================================================
# Target rules for targets named m_httpd.so

# Build rule for target.
m_httpd.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_httpd.so
.PHONY : m_httpd.so

# fast build rule for target.
m_httpd.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_httpd.so.dir/build.make modules/CMakeFiles/m_httpd.so.dir/build
.PHONY : m_httpd.so/fast

#=============================================================================
# Target rules for targets named os_forbid.so

# Build rule for target.
os_forbid.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_forbid.so
.PHONY : os_forbid.so

# fast build rule for target.
os_forbid.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_forbid.so.dir/build.make modules/CMakeFiles/os_forbid.so.dir/build
.PHONY : os_forbid.so/fast

#=============================================================================
# Target rules for targets named m_sql_oper.so

# Build rule for target.
m_sql_oper.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_sql_oper.so
.PHONY : m_sql_oper.so

# fast build rule for target.
m_sql_oper.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_sql_oper.so.dir/build.make modules/CMakeFiles/m_sql_oper.so.dir/build
.PHONY : m_sql_oper.so/fast

#=============================================================================
# Target rules for targets named m_rewrite.so

# Build rule for target.
m_rewrite.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m_rewrite.so
.PHONY : m_rewrite.so

# fast build rule for target.
m_rewrite.so/fast:
	$(MAKE) -f modules/CMakeFiles/m_rewrite.so.dir/build.make modules/CMakeFiles/m_rewrite.so.dir/build
.PHONY : m_rewrite.so/fast

#=============================================================================
# Target rules for targets named os_jupe.so

# Build rule for target.
os_jupe.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_jupe.so
.PHONY : os_jupe.so

# fast build rule for target.
os_jupe.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_jupe.so.dir/build.make modules/CMakeFiles/os_jupe.so.dir/build
.PHONY : os_jupe.so/fast

#=============================================================================
# Target rules for targets named hs_request.so

# Build rule for target.
hs_request.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hs_request.so
.PHONY : hs_request.so

# fast build rule for target.
hs_request.so/fast:
	$(MAKE) -f modules/CMakeFiles/hs_request.so.dir/build.make modules/CMakeFiles/hs_request.so.dir/build
.PHONY : hs_request.so/fast

#=============================================================================
# Target rules for targets named ms_info.so

# Build rule for target.
ms_info.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ms_info.so
.PHONY : ms_info.so

# fast build rule for target.
ms_info.so/fast:
	$(MAKE) -f modules/CMakeFiles/ms_info.so.dir/build.make modules/CMakeFiles/ms_info.so.dir/build
.PHONY : ms_info.so/fast

#=============================================================================
# Target rules for targets named os_modinfo.so

# Build rule for target.
os_modinfo.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_modinfo.so
.PHONY : os_modinfo.so

# fast build rule for target.
os_modinfo.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_modinfo.so.dir/build.make modules/CMakeFiles/os_modinfo.so.dir/build
.PHONY : os_modinfo.so/fast

#=============================================================================
# Target rules for targets named os_news.so

# Build rule for target.
os_news.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os_news.so
.PHONY : os_news.so

# fast build rule for target.
os_news.so/fast:
	$(MAKE) -f modules/CMakeFiles/os_news.so.dir/build.make modules/CMakeFiles/os_news.so.dir/build
.PHONY : os_news.so/fast

#=============================================================================
# Target rules for targets named webcpanel.so

# Build rule for target.
webcpanel.so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webcpanel.so
.PHONY : webcpanel.so

# fast build rule for target.
webcpanel.so/fast:
	$(MAKE) -f modules/webcpanel/CMakeFiles/webcpanel.so.dir/build.make modules/webcpanel/CMakeFiles/webcpanel.so.dir/build
.PHONY : webcpanel.so/fast

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) -f include/CMakeFiles/headers.dir/build.make include/CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f include/CMakeFiles/version.dir/build.make include/CMakeFiles/version.dir/build
.PHONY : version/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... services"
	@echo "... anopesmtp"
	@echo "... memoserv.so"
	@echo "... global.so"
	@echo "... botserv.so"
	@echo "... unreal4.so"
	@echo "... unreal.so"
	@echo "... plexus.so"
	@echo "... inspircd20.so"
	@echo "... hybrid.so"
	@echo "... charybdis.so"
	@echo "... bahamut.so"
	@echo "... m_xmlrpc.so"
	@echo "... m_sql_authentication.so"
	@echo "... m_regex_posix.so"
	@echo "... m_redis.so"
	@echo "... m_proxyscan.so"
	@echo "... m_helpchan.so"
	@echo "... m_dnsbl.so"
	@echo "... fantasy.so"
	@echo "... ns_maxemail.so"
	@echo "... enc_sha256.so"
	@echo "... enc_sha1.so"
	@echo "... enc_old.so"
	@echo "... enc_md5.so"
	@echo "... db_sql_live.so"
	@echo "... db_sql.so"
	@echo "... db_old.so"
	@echo "... db_flatfile.so"
	@echo "... os_update.so"
	@echo "... os_stats.so"
	@echo "... os_reload.so"
	@echo "... os_oper.so"
	@echo "... hs_set.so"
	@echo "... cs_mode.so"
	@echo "... ms_list.so"
	@echo "... ns_getemail.so"
	@echo "... cs_updown.so"
	@echo "... os_chankill.so"
	@echo "... os_shutdown.so"
	@echo "... os_ignore.so"
	@echo "... ratbox.so"
	@echo "... cs_suspend.so"
	@echo "... cs_xop.so"
	@echo "... m_dns.so"
	@echo "... cs_sync.so"
	@echo "... os_noop.so"
	@echo "... ns_access.so"
	@echo "... cs_unban.so"
	@echo "... cs_access.so"
	@echo "... bs_control.so"
	@echo "... ns_getpass.so"
	@echo "... bs_botlist.so"
	@echo "... hs_del.so"
	@echo "... cs_status.so"
	@echo "... m_xmlrpc_main.so"
	@echo "... bs_bot.so"
	@echo "... cs_akick.so"
	@echo "... os_svs.so"
	@echo "... cs_getkey.so"
	@echo "... hs_on.so"
	@echo "... operserv.so"
	@echo "... os_config.so"
	@echo "... hs_off.so"
	@echo "... cs_clone.so"
	@echo "... cs_set_misc.so"
	@echo "... ms_del.so"
	@echo "... ns_recover.so"
	@echo "... bs_assign.so"
	@echo "... bs_badwords.so"
	@echo "... bs_autoassign.so"
	@echo "... ms_rsend.so"
	@echo "... cs_info.so"
	@echo "... cs_invite.so"
	@echo "... os_akill.so"
	@echo "... gl_global.so"
	@echo "... os_set.so"
	@echo "... bs_kick.so"
	@echo "... hs_list.so"
	@echo "... bs_set.so"
	@echo "... os_oline.so"
	@echo "... cs_ban.so"
	@echo "... cs_statusupdate.so"
	@echo "... os_info.so"
	@echo "... nickserv.so"
	@echo "... cs_enforce.so"
	@echo "... os_logsearch.so"
	@echo "... os_sxline.so"
	@echo "... os_dns.so"
	@echo "... cs_list.so"
	@echo "... cs_topic.so"
	@echo "... greet.so"
	@echo "... hostserv.so"
	@echo "... cs_log.so"
	@echo "... cs_drop.so"
	@echo "... cs_entrymsg.so"
	@echo "... bs_info.so"
	@echo "... ms_send.so"
	@echo "... hs_group.so"
	@echo "... m_ssl_openssl.so"
	@echo "... cs_set.so"
	@echo "... os_module.so"
	@echo "... cs_flags.so"
	@echo "... ns_alist.so"
	@echo "... help.so"
	@echo "... ms_check.so"
	@echo "... inspircd12.so"
	@echo "... ms_ignore.so"
	@echo "... cs_kick.so"
	@echo "... ms_read.so"
	@echo "... ms_sendall.so"
	@echo "... ms_set.so"
	@echo "... enc_bcrypt.so"
	@echo "... ns_update.so"
	@echo "... ms_cancel.so"
	@echo "... os_kick.so"
	@echo "... ms_staff.so"
	@echo "... ngircd.so"
	@echo "... m_sql_log.so"
	@echo "... m_sasl.so"
	@echo "... os_session.so"
	@echo "... ns_ajoin.so"
	@echo "... ns_cert.so"
	@echo "... os_mode.so"
	@echo "... m_mysql.so"
	@echo "... ns_drop.so"
	@echo "... ns_group.so"
	@echo "... ns_resetpass.so"
	@echo "... os_list.so"
	@echo "... ns_identify.so"
	@echo "... os_login.so"
	@echo "... ns_info.so"
	@echo "... ns_list.so"
	@echo "... os_defcon.so"
	@echo "... ns_logout.so"
	@echo "... ns_register.so"
	@echo "... cs_seen.so"
	@echo "... ns_set.so"
	@echo "... ns_set_misc.so"
	@echo "... chanserv.so"
	@echo "... db_redis.so"
	@echo "... os_kill.so"
	@echo "... enc_none.so"
	@echo "... cs_register.so"
	@echo "... ns_status.so"
	@echo "... ns_suspend.so"
	@echo "... m_httpd.so"
	@echo "... os_forbid.so"
	@echo "... m_sql_oper.so"
	@echo "... m_rewrite.so"
	@echo "... os_jupe.so"
	@echo "... hs_request.so"
	@echo "... ms_info.so"
	@echo "... os_modinfo.so"
	@echo "... os_news.so"
	@echo "... webcpanel.so"
	@echo "... headers"
	@echo "... version"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

